<?php $title = "Clicks 2018"; ?>

<?php include 'snippets/header.php' ?>

<main>
	<div class="browser-recommend">
		<div class="window">
			<div class="popup text-center padding-15px d-flex flex-column align-items-center justify-content-center">
				<img class="margin-bottom-40px" src="assets/img/computer.png" alt="">
				<h5 class="white max-width-100">This site is best viewed on screen sizes larger than 15 inches, using the updated versions of respective browsers: <br><span class="dark-blue">Chrome, Safari, Firefox and Internet Explorer</span></h5>
				<img class="close" src="assets/img/exit.png" alt="">
			</div>
		</div>
	</div>
	
	<section class="banner-section">
		<div class="container banner-slider">
			<div class="banner banner-1 background-center">
				
			</div>
		</div>
		<div class="sky-blue-transparent-bg text-center small-content-padding">
			<h1 class="white text-uppercase margin-bottom-0">Integrated Annual Report <br><b>2018</b></h1>
		</div>
	</section>

	<section class="reports medium-content-padding">
		<div class="container">
			<div class="row d-flex">
				<div class="col-4 text-center margin-bottom-20px d-flex align-items-center justify-content-center">
					<a class="white text-uppercase dark-grey-bg d-block width-100" href="">
						Download the full <br><b><u>Integrated Annual Report</u></b> >>
					</a>
				</div>
				<div class="col-4 text-center margin-bottom-20px d-flex align-items-center justify-content-center">
					<a class="white text-uppercase dark-grey-bg d-block width-100" href="">
						Download the full <br><b><u>Annual Financial Statements</u></b> >>
					</a>
				</div>
				<div class="col-4 text-center margin-bottom-20px d-flex align-items-center justify-content-center">
					<a class="white text-uppercase dark-grey-bg d-block width-100" href="">
						Download the full <br><b><u>Five year Financial Revew</u></b> >>
					</a>
				</div>
			</div>
		</div>
	</section>

	<section class="container review small-content-padding">
		<div class="row">
			<div class="col-12 margin-bottom-20px text-center">
				<h3 class="sky-blue">Clicks Group is a retail-led healthcare group which is listed in the Food and Drug Retailers sector on the JSE.</h3>
			</div>
			<div class="col-4 d-flex margin-bottom-20px">
				<div class="dark-blue-border d-flex align-items-center justify-content-center text-center width-100">
					<p class="margin-bottom-0">Cash generated by operations exceeds <br><b class="larger sky-blue">R2 billion</b></p>
				</div>
			</div>
			<div class="col-4 d-flex margin-bottom-20px">
				<div class="dark-blue-border d-flex align-items-center justify-content-center text-center width-100">
					<p class="margin-bottom-0">Diluted HEPS up <br><b class="green larger">14.5%</b> <br>to 502 cents</p>
				</div>
			</div>
			<div class="col-4 d-flex margin-bottom-20px">
				<div class="dark-blue-border d-flex align-items-center justify-content-center text-center width-100">
					<p class="margin-bottom-0">Dividend up <br><b class="blue larger">18.4%</b> <br>to 322 cents per share</p>
				</div>
			</div>
			<div class="col-4 d-flex margin-bottom-20px">
				<div class="dark-blue-border d-flex align-items-center justify-content-center text-center width-100">
					<p class="margin-bottom-0"><b class="larger blue">R7.5 billion</b> shareholder value created</p>
				</div>
			</div>
			<div class="col-4 d-flex margin-bottom-20px">
				<div class="dark-blue-border d-flex align-items-center justify-content-center text-center width-100">
					<p class="margin-bottom-0"><b class="larger green">R518 million</b> <br>capital investment</p>
				</div>
			</div>
			<div class="col-4 d-flex margin-bottom-20px">
				<div class="dark-blue-border d-flex align-items-center justify-content-center text-center width-100">
				<p class="margin-bottom-0">Opened <b class="larger sky-blue">111</b> Clicks stores and expanded footprint to 622 stores</p>
				</div>
			</div>
			<div class="col-4 d-flex margin-bottom-20px">
				<div class="dark-blue-border d-flex align-items-center justify-content-center text-center width-100">
					<p class="margin-bottom-0"><b class="larger green">R7 million</b> active Clicks ClubCard loyalty members</p>
				</div>
			</div>
			<div class="col-4 d-flex margin-bottom-20px">
				<div class="dark-blue-border d-flex align-items-center justify-content-center text-center width-100">
					<p class="margin-bottom-0"><b class="larger blue">Level 5 BBBEE</b> <br>rating under new codes</p>
				</div>
			</div>
			<div class="col-4 d-flex margin-bottom-20px">
				<div class="dark-blue-border d-flex align-items-center justify-content-center text-center width-100">
				<p class="margin-bottom-0">First-time inclusion in <b class="larger green">FTSE4Good <br>Index</b></p>
				</div>
			</div>
		</div>
	</section>

	<section class="container">
		<div class="dash">
			<div class="green-bg circle d-flex align-items-center justify-content-center">
				<img src="assets/img/down-arrow.svg" alt="Down arrow">
			</div>
		</div>
	</section>

	<section class="container creating-value medium-content-padding">
		<div class="row">
			<div class="col-6 col-lg-5 d-flex flex-column justify-content-center align-items-start">
				<h2 class="dark-blue text-uppercase">Creating <br><span class="sky-blue">value in 2018</span></h2>
				<a href="" class="btn grey-btn">Read full report <span class="sky-blue">>></span></a>
			</div>
			<div class="col-6 col-lg-7">
				<img src="assets/img/homepage/creating_value.jpg" alt="Creating value">
			</div>
		</div>
		<div class="row small-content-padding">
			<div class="col-12">
				<h3 class="text-uppercase sky-blue">Listen</h3>
				<div class="dash"></div>
			</div>
			<div class="col-7">
				<p>PODCAST – FINANCIAL RESULTS >> Clicks delivered another strong trading performance in tough retail conditions, reporting good volume growth and increased market shares in all product categories. </p>
			</div>
			<div class="col-5 d-flex align-items-center justify-content-center">
				<audio src="" type="audio/mp3" controls></audio>
			</div>
		</div>
	</section>

	<section class="light-blue-bg large-content-padding group-profile">
		<div class="container">
			<div class="row">
				<div class="col-12 col-lg-5 col-xl-4">
					<h2 class="text-uppercase">Group profile</h2>
					<h4 class="blue">Clicks Group is a retail-led healthcare group which is listed in the Food and Drug Retailers sector on the JSE.</h4>
					<p>Founded in 1968, the group has been listed on the JSE since 1996. Following changes in South African legislation in 2003 to allow corporate pharmacy ownership, the group entered the retail pharmacy market with the opening of the first Clicks pharmacy in 2004.</p>
					<p>The group is today a leader in the healthcare market where Clicks is the country’s largest pharmacy chain with 473 in-store pharmacies and a 22.2% share of the retail pharmacy market. UPD has a 25.6% share of the private pharmaceutical wholesale market.</p>
					<a href="" class="btn grey-btn margin-bottom-20px">Read full report <span class="sky-blue">>></span></a>
				</div>
				<div class="col-12 col-lg-7 col-xl-8 d-flex flex-column align-items-center justify-content-center">
					<img class="medium-content-padding" src="assets/img/homepage/group_profile_image1.png" alt="Group Profile">
					<div class="row remove-flex width-100">
						<div class="col-4 text-center d-flex flex-column align-items-center justify-content-center dark-blue-border-top dark-blue-border-bottom">
							<p><b class="larger green">17.2%</b> <br>diluted HEPS <br>10-year CAGR</p>
						</div>
						<div class="col-4 text-center d-flex flex-column align-items-center justify-content-center">
							<div class="white-bg box-padding">
								<p><b class="larger blue">20.9%</b> <br>dividend per share <br>10-year CAGR</p>
							</div>
						</div>
						<div class="col-4 text-center d-flex flex-column align-items-center justify-content-center dark-blue-border-top dark-blue-border-bottom">
							<p><b class="larger green">28.9%</b> <br>total shareholder return <br>10-year CAGR</p>
						</div>
					</div>
				</div>
				<div class="col-12 small-content-padding">
					<h3 class="text-uppercase blue">Watch</h3>
					<div class="dash"></div>
				</div>
				<div class="col-6">
					<div class="video-block video-trigger" data-video-trigger="1">
						<div class="thumbnail">
							<img src="assets/img/homepage/thumbnail1.jpg" alt="Video 1">
							<img class="icon" src="assets/img/video_icon.png" alt="Play button">
						</div>
						<p>Clicks descriptor here…</p>
					</div>
				</div>
				<div class="col-6">
					<div class="video-block video-trigger" data-video-trigger="2">
						<div class="thumbnail">
							<img src="assets/img/homepage/thumbnail2.jpg" alt="Video 2">
							<img class="icon" src="assets/img/video_icon.png" alt="Play button">
						</div>
						<p>Clicks descriptor here…</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	
	<section class="container large-content-padding leadership">
		<div class="row">
			<div class="col-12">
				<h2 class="text-uppercase">Leadership</h2>
				<div class="dash"></div>
				<div class="thick-light-blue-border">
					<div class="row">
						<div class="col-4 col-xl-3">
							<img src="assets/img/homepage/Chairman.png" alt="Chairman">
						</div>
						<div class="col-7 col-xl-8 medium-content-padding">
							<h3 class="heading-4 text-uppercase"><b>Chairman's Report</b></h3>
							<p class="margin-bottom-0">In a year marked by significant political instability and uncertainty, deteriorating economic conditions and consequent credit ratings downgrades, financial pressure on South African consumers has continued to intensify. </p>
							<a href="" class="btn grey-btn">Read full report <span class="sky-blue">>></span></a>
						</div>
					</div>
				</div>
				<div class="thick-light-blue-border">
					<div class="row">
						<div class="offset-1 col-7 col-xl-8 medium-content-padding">
							<h3 class="heading-4 text-uppercase"><b>Chief Executive's Report</b></h3>
							<p class="margin-bottom-0">Clicks delivered another strong trading performance in tough retail conditions, reporting good volume growth and increased market shares in all product categories. The brand continues to demonstrate its resilience in the current constrained spending environment, with healthcare being a necessity and beauty an affordable luxury.</p>
							<a href="" class="btn grey-btn">Read full report <span class="sky-blue">>></span></a>
						</div>
						<div class="col-4 col-xl-3">
							<img src="assets/img/homepage/CEO.png" alt="CEO">
						</div>
					</div>
				</div>
				<div class="thick-light-blue-border">
					<div class="row">
						<div class="col-4 col-xl-3">
							<img src="assets/img/homepage/CFO.png" alt="CFO">
						</div>
						<div class="col-7 col-xl-8 medium-content-padding">
							<h3 class="heading-4 text-uppercase"><b>Chief Financial Officer's Report</b></h3>
							<p class="margin-bottom-0">Clicks Group delivered another resilient performance in tough retail trading conditions, highlighted by robust health and beauty sales, increased margins, strong cash flows and enhanced returns to shareholders.</p>
							<a href="" class="btn grey-btn">Read full report <span class="sky-blue">>></span></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="light-blue-bg business-review large-content-padding">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<h2 class="text-uppercase">Business review</h2>
					<div class="dash"></div>
					<div class="row">
						<div class="col-6 dark-blue-border-right text-center">
							<img class="margin-bottom-20px" src="assets/img/clicks.png" alt="Clicks logo" style="width: 220px;">
						</div>
						<div class="col-6 text-center">
							<img class="margin-bottom-20px" src="assets/img/upd.png" alt="UPD logo" style="width: 220px;">
						</div>
						<div class="col-6 dark-blue-border-right text-center d-flex flex-column justify-content-between align-items-center">
							<p class="margin-bottom-0 width-100">“Clicks produced another strong trading performance, led by pharmacy and front shop health sales. Customers continued to respond positively to the Clicks value promotions and differentiated product ranges as the chain reported strong volume growth while gaining market share in all product categories.”</p>
							<a href="" class="btn grey-btn">Read full report <span class="sky-blue">>></span></a>
						</div>
						<div class="col-6 text-center d-flex flex-column justify-content-between align-items-center">
							<p class="margin-bottom-0 width-100">“UPD delivered double-digit sales and profit growth for the year, driven by good growth in the wholesale business. Reported turnover increased by 11.4% and UPD maintained its market-leading positions in both the pharmaceutical wholesale and bulk distribution markets.”</p>
							<a href="" class="btn grey-btn">Read full report <span class="sky-blue">>></span></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="container medium-content-padding">
		<div class="row">
			<div class="col-12">
				<h2 class="text-uppercase">Governance</h2>
				<div class="dash"></div>
			</div>
			<div class="col-12 col-xl-6">
				<h4><a href="" class="blue">Creating value through good governance</a></h4>
				<h4><a href="" class="blue">Rewarding value creation</a></h4>
				<h4><a href="" class="blue">Social and ethics committee report</a></h4>
				<h4><a href="" class="blue">Shareholder analysis</a></h4>
				<h4><a href="" class="blue">Shareholders’ diary</a></h4>
				<h4><a href="" class="blue">Corporate information</a></h4>
			</div>
			<div class="col-12 col-xl-6">
				<div class="row">
					<div class="col-6 d-flex margin-bottom-20px">
						<a href="" class="thick-light-blue-border box-padding text-center d-flex flex-column justify-content-center align-items-center width-100">
							<h4 class="text-uppercase width-100">Summary of the audited financial statements</h4>
							<div href="" class="btn grey-btn margin-top-0">Read full report <span class="sky-blue">>></span></div>
						</a>
					</div>
					<div class="col-6 d-flex margin-bottom-20px">
						<a href="" class="thick-light-blue-border box-padding text-center d-flex flex-column justify-content-center align-items-center width-100">
							<h4 class="text-uppercase width-100">Download the full audited financial statements</h4>
							<div class="row width-100">
								<div class="col-8">
									<p class="text-uppercase width-100">Download</p>
								</div>
								<div class="col-4">
									<img src="assets/img/pdficon.png" alt="PDF Icon" style="width: 40px;">
								</div>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-12 small-content-padding">
				<h3 class="sky-blue text-uppercase">Watch</h3>
				<div class="dash"></div>
			</div>
			<div class="col-4">
				<div class="video-block margin-bottom-40px video-trigger" data-video-trigger="3">
					<div class="thumbnail">
						<img src="assets/img/homepage/great_value.jpg" alt="Video 2">
						<img class="icon" src="assets/img/video_icon.png" alt="Play button">
					</div>
					<p>Great Value</p>
				</div>
			</div>
			<div class="col-4">
				<div class="video-block margin-bottom-40px video-trigger" data-video-trigger="4">
					<div class="thumbnail">
						<img src="assets/img/homepage/convenience.jpg" alt="Video 2">
						<img class="icon" src="assets/img/video_icon.png" alt="Play button">
					</div>
					<p>Convenience</p>
				</div>
			</div>
			<div class="col-4">
				<div class="video-block margin-bottom-40px video-trigger" data-video-trigger="5">
					<div class="thumbnail">
						<img src="assets/img/homepage/club_card.jpg" alt="Video 2">
						<img class="icon" src="assets/img/video_icon.png" alt="Play button">
					</div>
					<p>Club Card</p>
				</div>
			</div>
			<div class="col-4">
				<div class="video-block margin-bottom-40px video-trigger" data-video-trigger="6">
					<div class="thumbnail">
						<img src="assets/img/homepage/product_development.jpg" alt="Video 2">
						<img class="icon" src="assets/img/video_icon.png" alt="Play button">
					</div>
					<p>Product Development</p>
				</div>
			</div>
			<div class="col-4">
				<div class="video-block margin-bottom-40px video-trigger" data-video-trigger="7">
					<div class="thumbnail">
						<img src="assets/img/homepage/develop_people.jpg" alt="Video 2">
						<img class="icon" src="assets/img/video_icon.png" alt="Play button">
					</div>
					<p>Developing Our People</p>
				</div>
			</div>
			<div class="col-4">
				<div class="video-block margin-bottom-40px video-trigger" data-video-trigger="8">
					<div class="thumbnail">
						<img src="assets/img/homepage/helping_hands.jpg" alt="Video 1">
						<img class="icon" src="assets/img/video_icon.png" alt="Play button">
					</div>
					<p>Helping Hands</p>
				</div>
			</div>
		</div>
	</section>

	<section class="medium-content-padding clicks-exp light-blue-bg">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<h2 class="text-uppercase">The Clicks Experience</h2>
				</div>
				<div class="col-12">
					<div class="clicks-slider margin-bottom-20px">
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/gallery/Clicks-Experience-Gallery.jpg);">
							<p class="white">Clicks operates 622 stores in destination and convenience formats.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/gallery/Clicks-Experience-Gallery2.jpg);">
							<p class="white">In both formats the beauty department is the start of the customer journey through our store.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/gallery/Clicks-Experience-Gallery3.jpg);">
							<p class="white">We have a growing presence in the fragrance market.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/gallery/Clicks-Experience-Gallery4.jpg);">
							<p class="white">Sorbet is one of our exclusive brands in partnership with Sorbet salons, South Africa’s leading beauty salon brand.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/gallery/Clicks-Experience-Gallery5.jpg);">
							<p class="white">The Clicks Group operates the franchise for The Body Shop in southern Africa. There are 53 standalone stores and a presence in 122 Clicks stores.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/gallery/Clicks-Experience-Gallery6.jpg);">
							<p class="white">Clicks has over 3 000 private label products.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homhomepagee/gallery/Clicks-Experience-Gallery7.jpg);">
							<p class="white">Clicks runs more health and beauty promotions than any other retailer.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/gallery/Clicks-Experience-Gallery8.jpg);">
							<p class="white">Baby is a strategically important category to attract new customers.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/gallery/Clicks-Experience-Gallery9.jpg);">
							<p class="white">Baby is a strategically important category to attract new customers.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/gallery/Clicks-Experience-Gallery10.jpg);">
							<p class="white">We are the market leader in toiletries.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/gallery/Clicks-Experience-Gallery11.jpg);">
							<p class="white">We are the market leader in toiletries.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/gallery/Clicks-Experience-Gallery12.jpg);">
							<p class="white">GNC is our leading exclusive brand in supplements. </p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/gallery/Clicks-Experience-Gallery13.jpg);">
							<p class="white">Pharmacies are in 473 of our stores.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/gallery/Clicks-Experience-Gallery14.jpg);">
							<p class="white">We operate clinics in 195 of our stores.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/gallery/Clicks-Experience-Gallery15.jpg);">
							<p class="white">We are the market leader in small electrical appliances.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/gallery/Clicks-Experience-Gallery16.jpg);">
							<p class="white">We employ over 14 000 people in Clicks.</p>
						</div>
					</div>
					<div class="clicks-nav light-grey-bg">
						<div class="nav-slide">
							<img src="assets/img/homepage/gallery/nav/Clicks-Experience-Gallery.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/gallery/nav/Clicks-Experience-Gallery2.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/gallery/nav/Clicks-Experience-Gallery3.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/gallery/nav/Clicks-Experience-Gallery4.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/gallery/nav/Clicks-Experience-Gallery5.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/gallery/nav/Clicks-Experience-Gallery6.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/gallery/nav/Clicks-Experience-Gallery7.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/gallery/nav/Clicks-Experience-Gallery8.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/gallery/nav/Clicks-Experience-Gallery9.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/gallery/nav/Clicks-Experience-Gallery10.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/gallery/nav/Clicks-Experience-Gallery11.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/gallery/nav/Clicks-Experience-Gallery12.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/gallery/nav/Clicks-Experience-Gallery13.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/gallery/nav/Clicks-Experience-Gallery14.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/gallery/nav/Clicks-Experience-Gallery15.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/gallery/nav/Clicks-Experience-Gallery16.jpg" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>
	</section> 

</main>

<div class="popups">
	<div class="popup video-1"></div>
	<div class="popup video-2"></div>
	<div class="popup video-3"></div>
	<div class="popup video-4"></div>
	<div class="popup video-5"></div>
	<div class="popup video-6"></div>
	<div class="popup video-7"></div>
	<div class="popup video-8"></div>
</div>

<?php include 'snippets/footer.php' ?>