<?php $title = "Clicks 2018"; ?>

<?php include 'snippets/header.php' ?>

<main>
	<div class="browser-recommend">
		<div class="window">
			<div class="popup text-center padding-15px d-flex flex-column align-items-center justify-content-center">
				<img class="margin-bottom-40px" src="assets/img/computer.png" alt="">
				<h5 class="white max-width-100">This site is best viewed on screen sizes larger than 15 inches, using the updated versions of respective browsers: <br><span class="dark-blue">Chrome, Safari, Firefox and Internet Explorer</span></h5>
				<img class="close" src="assets/img/exit.png" alt="">
			</div>
		</div>
	</div>
	
	<section class="banner-section">
		<div class="container banner-slider">
			<div class="banner banner-1 background-center">
				
			</div>
			<div class="banner banner-2 background-center">
				
			</div>
			<div class="banner banner-3 background-center">
				
			</div>
			<div class="banner banner-4 background-center">
				
			</div>
			<div class="banner banner-5 background-center">
				
			</div>
		</div>
		<div class="sky-blue-transparent-bg text-center small-content-padding">
			<h1 class="white text-uppercase margin-bottom-0">Integrated Annual Report <br><b>2018</b></h1>
		</div>
	</section>

	<section class="reports medium-content-padding">
		<div class="container">
			<div class="row d-flex">
				<div class="col-4 text-center margin-bottom-20px d-flex align-items-center justify-content-center">
					<a class="white text-uppercase dark-grey-bg d-block width-100" href="assets/pdfs/online_reports/Clicks_IAR_2018_Online.pdf" target="_blank">
						Download the full <br><b><u>Integrated Annual Report</u></b> >>
					</a>
				</div>
				<div class="col-4 text-center margin-bottom-20px d-flex align-items-center justify-content-center">
					<a class="white text-uppercase dark-grey-bg d-block width-100" href="assets/pdfs/online_reports/Clicks_AFS_2018_online.pdf" target="_blank">
						Download the full <br><b><u>Annual Financial Statements</u></b> >>
					</a>
				</div>
				<div class="col-4 text-center margin-bottom-20px d-flex align-items-center justify-content-center">
					<a class="white text-uppercase dark-grey-bg d-block width-100" href="assets/pdfs/online_reports/Clicks_Five_Year_2018_online.pdf" target="_blank">
						Download the full <br><b><u>Five year Financial Review</u></b> >>
					</a>
				</div>
			</div>
		</div>
	</section>

	<section class="container review small-content-padding">
		<div class="row">
			<div class="col-12 margin-bottom-20px text-center">
				<h3 class="sky-blue">Clicks Group is a retail-led healthcare group which is listed in the Food and Drug Retailers sector on the JSE.</h3>
			</div>
			<div class="col-12">
				<div class="dash"></div>
			</div>
			<div class="col-6 d-flex  dark-blue-border-right">
				<div class="d-flex align-items-center justify-content-center text-center width-100 box-padding">
					<h4 class="margin-bottom-0">Group turnover up <br><b class="xl larger green">9.1%</b></h4>
				</div>
			</div>
			<div class="col-6 d-flex ">
				<div class="d-flex align-items-center justify-content-center text-center width-100 box-padding">
					<h4 class="margin-bottom-0">Health and beauty sales up <br><b class="blue larger xl">11.7%</b></h4>
				</div>
			</div>
			<div class="col-12">
				<div class="dash"></div>
			</div>
			<div class="col-6 d-flex dark-blue-border-right">
				<div class="d-flex align-items-center justify-content-center text-center width-100 box-padding">
					<h4 class="margin-bottom-0">Cash generated by operations <br><b class="sky-blue larger xl">R2.5 billion</b></h4>
				</div>
			</div>
			<div class="col-6 d-flex">
				<div class="d-flex align-items-center justify-content-center text-center width-100 box-padding">
					<h4 class="margin-bottom-0">Diluted HEPS up <br><b class="green larger xl">15.1%</b></h4>
				</div>
			</div>
			<div class="col-12">
				<div class="dash"></div>
			</div>
			<div class="col-6 d-flex dark-blue-border-right">
				<div class="d-flex align-items-center justify-content-center text-center width-100 box-padding">
					<h4 class="margin-bottom-0">Total dividend up <br><b class="blue larger xl">18.0%</b></h3>
				</div>
			</div>
			<div class="col-6 d-flex ">
				<div class="d-flex align-items-center justify-content-center text-center width-100 box-padding">
				<h4 class="margin-bottom-0">Included in <br><b class="sky-blue larger xl">FTSE/JSE Top 40 Index</b></h4>
				</div>
			</div>
		</div>
	</section>

	<section class="container">
		<div class="dash">
			<div class="green-bg circle d-flex align-items-center justify-content-center">
				<img src="assets/img/down-arrow.svg" alt="Down arrow">
			</div>
		</div>
	</section>

	<section class="container creating-value medium-content-padding">
		<div class="row">
			<div class="col-6 col-lg-5 d-flex flex-column justify-content-center align-items-start">
				<h2 class="dark-blue text-uppercase">Creating <br><span class="sky-blue">value in 2018</span></h2>
				<a href="pages/about/creating_value" class="btn grey-btn">Read full report <span class="sky-blue">>></span></a>
			</div>
			<div class="col-6 col-lg-7">
				<a href="assets/img/homepage/creating_value.jpg" target="_blank" class="img-enlarge width-100">
					<img src="assets/img/homepage/creating_value.jpg" alt="">
				</a>
			</div>
		</div>
	</section>

	<section class="light-blue-bg large-content-padding group-profile">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<h2 class="text-uppercase">Group profile</h2>
					<h4 class="blue">Clicks Group is a retail-led healthcare group which is listed in the Food and Drug Retailers sector on the JSE.</h4>
					<p>Founded 50 years ago in 1968, the group has been listed on the JSE since 1996. Following changes in South African legislation in 2003 to allow corporate pharmacy ownership, the group entered the retail pharmacy market with the opening of the first Clicks pharmacy in 2004. Today the group is a leader in the healthcare market, in both retail pharmacy and pharmaceutical wholesaling.</p>
					<a href="pages/about/group_profile" class="btn grey-btn margin-bottom-20px">Read full report <span class="sky-blue">>></span></a>
				</div>
				<div class="col-10 offset-1 d-flex flex-column align-items-center justify-content-center medium-content-padding">
					<div class="row remove-flex width-100">
						<div class="col-4 text-center d-flex flex-column align-items-center justify-content-center dark-blue-border-top dark-blue-border-bottom">
							<h5><span class="larger xl green">16.0%</span> <br>diluted HEPS <br>10-year CAGR</h5>
						</div>
						<div class="col-4 text-center d-flex flex-column align-items-center justify-content-center">
							<div class="white-bg box-padding medium-content-padding">
								<h5><span class="larger xl blue">32.5%</span> <br>total shareholder return <br>10-year CAGR</h5>
							</div>
						</div>
						<div class="col-4 text-center d-flex flex-column align-items-center justify-content-center dark-blue-border-top dark-blue-border-bottom">
							<h5><span class="larger xl sky-blue">20.1%</span> <br>dividend per share <br>10-year CAGR</h5>
						</div>
					</div>
				</div>
				<div class="col-12 small-content-padding">
					<h3 class="text-uppercase blue">Watch</h3>
					<div class="dash"></div>
				</div>
				<div class="col-6">
					<div class="video-block video-trigger" data-video-trigger="1">
						<div class="thumbnail">
							<img src="assets/img/homepage/thumbnail1.jpg" alt="Video 1">
							<img class="icon" src="assets/img/video_icon.png" alt="Play button">
						</div>
						<p>Clicks descriptor here…</p>
					</div>
				</div>
				<div class="col-6">
					<div class="video-block video-trigger" data-video-trigger="2">
						<div class="thumbnail">
							<img src="assets/img/homepage/thumbnail2.jpg" alt="Video 2">
							<img class="icon" src="assets/img/video_icon.png" alt="Play button">
						</div>
						<p>Clicks descriptor here…</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	
	<section class="container large-content-padding leadership">
		<div class="row">
			<div class="col-12">
				<h2 class="text-uppercase">Leadership</h2>
				<div class="dash"></div>
				<div class="thick-light-blue-border">
					<div class="row">
						<div class="col-4 col-xl-3">
							<img src="assets/img/leadership/david_nurek_cutout.png" alt="Chairman" style="width: 220px;">
						</div>
						<div class="col-7 col-xl-8 medium-content-padding">
							<h3 class="heading-4 text-uppercase"><b>Chairman's Report</b></h3>
							<p class="margin-bottom-0">In an environment of low growth, deteriorating economic conditions and constrained consumer spending, the group produced another excellent performance and entrenched its position as the country’s foremost health and beauty retailer. </p>
							<a href="pages/leadership/chairmans_report" class="btn grey-btn">Read full report <span class="sky-blue">>></span></a>
						</div>
					</div>
				</div>
				<div class="thick-light-blue-border">
					<div class="row">
						<div class="offset-1 col-7 col-xl-8 medium-content-padding">
							<h3 class="heading-4 text-uppercase"><b>Chief Executive's Report</b></h3>
							<p class="margin-bottom-0">2018 marked the 50th birthday of the founding of Clicks by visionary retailer, Jack Goldin, who opened the first store in August 1968 in the Cape Town city centre.</p>
							<a href="pages/leadership/ceo_report" class="btn grey-btn">Read full report <span class="sky-blue">>></span></a>
						</div>
						<div class="col-4 col-xl-3">
							<img src="assets/img/leadership/david_kneale_cutout.png" alt="CEO" style="width: 250px;">
						</div>
					</div>
				</div>
				<div class="thick-light-blue-border">
					<div class="row">
						<div class="col-4 col-xl-3">
							<img src="assets/img/leadership/p36_michael_fleming.png" alt="CFO" style="width: 230px;">
						</div>
						<div class="col-7 col-xl-8 medium-content-padding">
							<h3 class="heading-4 text-uppercase"><b>Chief Financial Officer's Report</b></h3>
							<p class="margin-bottom-0">Clicks Group continued its strong growth momentum with robust turnover growth supported by good management of margins, expenses and working capital, and continued strong cash generation.</p>
							<a href="pages/leadership/cfo_report" class="btn grey-btn">Read full report <span class="sky-blue">>></span></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="light-blue-bg business-review large-content-padding">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<h2 class="text-uppercase">Business review</h2>
					<div class="dash"></div>
					<div class="row">
						<div class="col-6 dark-blue-border-right text-center">
							<img class="margin-bottom-20px" src="assets/img/clicks.png" alt="Clicks logo" style="width: 220px;">
						</div>
						<div class="col-6 text-center">
							<img class="margin-bottom-20px" src="assets/img/upd.png" alt="UPD logo" style="width: 220px;">
						</div>
						<div class="col-6 dark-blue-border-right text-center d-flex flex-column justify-content-between align-items-center">
							<p class="margin-bottom-0 width-100">“Clicks delivered another resilient performance in the increasingly constrained consumer spending environment. The strength of the Clicks brand and its loyal customer base contributed to health and beauty sales increasing by 11.7%, with volume growth of 5.1% in same stores, as Clicks gained market share in all product categories.”</p>
							<a href="pages/business_review/clicks" class="btn grey-btn">Read full report <span class="sky-blue">>></span></a>
						</div>
						<div class="col-6 text-center d-flex flex-column justify-content-between align-items-center">
							<p class="margin-bottom-0 width-100">“UPD maintained its market-leading positions in both the pharmaceutical wholesale and bulk distribution markets as the business gained market share, secured new distribution clients and reported ongoing excellent control of inventory and costs.”</p>
							<a href="pages/business_review/upd" class="btn grey-btn">Read full report <span class="sky-blue">>></span></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="container medium-content-padding">
		<div class="row">
			<div class="col-12">
				<h2 class="text-uppercase">Governance</h2>
				<div class="dash"></div>
			</div>
			<div class="col-12 col-xl-6">
				<h4><a href="pages/governance/create_value_governance.php" class="blue">Creating value through good governance</a></h4>
				<h4><a href="pages/governance/create_value_citizenship.php" class="blue">Creating value through good citizenship</a></h4>
				<h4><a href="pages/governance/create_value_stakeholder.php" class="blue">Creating value through stakeholder engagement</a></h4>
				<h4><a href="pages/governance/rewarding_value.php" class="blue">Rewarding value </a></h4>
			</div>
			<div class="col-12 col-xl-6">
				<div class="row">
					<div class="col-6 d-flex margin-bottom-20px">
						<a href="" class="thick-light-blue-border box-padding text-center d-flex flex-column justify-content-center align-items-center width-100">
							<h4 class="text-uppercase width-100">Summary of the audited financial statements</h4>
							<div href="" class="btn grey-btn margin-top-0">Read full report <span class="sky-blue">>></span></div>
						</a>
					</div>
					<div class="col-6 d-flex margin-bottom-20px">
						<a href="" class="thick-light-blue-border box-padding text-center d-flex flex-column justify-content-center align-items-center width-100">
							<h4 class="text-uppercase width-100">Download the full audited financial statements</h4>
							<div class="row width-100">
								<div class="col-8">
									<p class="text-uppercase width-100">Download</p>
								</div>
								<div class="col-4">
									<img src="assets/img/pdficon.png" alt="PDF Icon" style="width: 40px;">
								</div>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="light-blue-bg business-review large-content-padding">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<h2 class="text-uppercase">Shareholder information</h2>
					<div class="dash"></div>
					<div class="row">
						<div class="col-12">
							<h4 class="blue margin-bottom-40px">Clicks Group has proven to be increasingly attractive to international investors over the past decade and 70% of the group’s shares are now held by offshore fund managers.</h4>
						</div>
						<div class="col-4 text-center dark-blue-border-right flex-column d-flex align-items-center justify-content-center">
							<h3 class="heading-4 margin-bottom-0 small-content-padding">Shareholder analysis</h3>
							<a href="pages/shareholder/shareholder_analysis" class="btn grey-btn margin-top-0">Read full report <span class="sky-blue">>></span></a>
						</div>
						<div class="col-4 dark-blue-border-right text-center flex-column d-flex align-items-center justify-content-center">
							<h3 class="heading-4 margin-bottom-0 small-content-padding">Shareholders' diary</h3>
							<a href="pages/shareholder/shareholder_diary" class="btn grey-btn margin-top-0">Read full report <span class="sky-blue">>></span></a>
						</div>
						<div class="col-4 text-center d-flex flex-column align-items-center justify-content-center">
							<h3 class="heading-4 margin-bottom-0 small-content-padding">Corporate information</h3>
							<a href="pages/shareholder/corporate_information" class="btn grey-btn margin-top-0">Read full report <span class="sky-blue">>></span></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="container medium-content-padding">
		<div class="row">
			<div class="col-12">
					<h3 class="sky-blue text-uppercase">Watch</h3>
					<div class="dash"></div>
				</div>
				<div class="col-4">
					<div class="video-block margin-bottom-40px video-trigger" data-video-trigger="3">
						<div class="thumbnail">
							<img src="assets/img/homepage/great_value.jpg" alt="Video 2">
							<img class="icon" src="assets/img/video_icon.png" alt="Play button">
						</div>
						<p>Great Value</p>
					</div>
				</div>
				<div class="col-4">
					<div class="video-block margin-bottom-40px video-trigger" data-video-trigger="4">
						<div class="thumbnail">
							<img src="assets/img/homepage/convenience.jpg" alt="Video 2">
							<img class="icon" src="assets/img/video_icon.png" alt="Play button">
						</div>
						<p>Convenience</p>
					</div>
				</div>
				<div class="col-4">
					<div class="video-block margin-bottom-40px video-trigger" data-video-trigger="5">
						<div class="thumbnail">
							<img src="assets/img/homepage/club_card.jpg" alt="Video 2">
							<img class="icon" src="assets/img/video_icon.png" alt="Play button">
						</div>
						<p>Club Card</p>
					</div>
				</div>
				<div class="col-4">
					<div class="video-block margin-bottom-40px video-trigger" data-video-trigger="6">
						<div class="thumbnail">
							<img src="assets/img/homepage/product_development.jpg" alt="Video 2">
							<img class="icon" src="assets/img/video_icon.png" alt="Play button">
						</div>
						<p>Product Development</p>
					</div>
				</div>
				<div class="col-4">
					<div class="video-block margin-bottom-40px video-trigger" data-video-trigger="7">
						<div class="thumbnail">
							<img src="assets/img/homepage/develop_people.jpg" alt="Video 2">
							<img class="icon" src="assets/img/video_icon.png" alt="Play button">
						</div>
						<p>Developing Our People</p>
					</div>
				</div>
				<div class="col-4">
					<div class="video-block margin-bottom-40px video-trigger" data-video-trigger="8">
						<div class="thumbnail">
							<img src="assets/img/homepage/helping_hands.jpg" alt="Video 1">
							<img class="icon" src="assets/img/video_icon.png" alt="Play button">
						</div>
						<p>Helping Hands</p>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="medium-content-padding clicks-exp light-blue-bg">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<h2 class="text-uppercase">The Clicks Experience</h2>
				</div>
				<div class="col-12">
					<div class="clicks-slider margin-bottom-20px">
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/new_gallery/2018-Gallery.jpg);">
						<p class="white">Clicks operates 663 stores in destination and convenience formats.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/new_gallery/2018-Gallery2.jpg);">
							<p class="white">In both formats the beauty department is the start of the customer journey through our store.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/new_gallery/2018-Gallery3.jpg);">
							<p class="white">We have a growing presence in the fragrance market.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/new_gallery/2018-Gallery4.jpg);">
							<p class="white"></p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/new_gallery/2018-Gallery5.jpg);">
							<p class="white">The Clicks Group operates the franchise for The Body Shop in southern Africa. There are 59 standalone stores and a presence in 170 Clicks stores.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/new_gallery/2018-Gallery6.jpg);">
							<p class="white">Sorbet is one of our exclusive brands in partnership with Sorbet salons, South Africa’s leading beauty salon brand.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/new_gallery/2018-Gallery7.jpg);">
							<p class="white">Clicks runs more health and beauty promotions than any other retailer.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/new_gallery/2018-Gallery8.jpg);">
							<p class="white">Baby is a strategically important category to attract new customers.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/new_gallery/2018-Gallery9.jpg);">
							<p class="white">Baby is a strategically important category to attract new customers.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/new_gallery/2018-Gallery10.jpg);">
							<p class="white">We are the market leader in toiletries.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/new_gallery/2018-Gallery11.jpg);">
							<p class="white">We are the market leader in toiletries.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/new_gallery/2018-Gallery12.jpg);">
							<p class="white">GNC is our leading exclusive brand in supplements.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/new_gallery/2018-Gallery13.jpg);">
							<p class="white">Pharmacies are in 510 of our stores.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/new_gallery/2018-Gallery14.jpg);">
							<p class="white">Clicks has over 4800 private label products.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/new_gallery/2018-Gallery15.jpg);">
							<p class="white">We operate clinics in 203 of our stores.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/new_gallery/2018-Gallery16.jpg);">
							<p class="white">We are the market leader in small electrical appliances.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/new_gallery/2018-Gallery17.jpg);">
							<p class="white"></p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/homepage/new_gallery/2018-Gallery18.jpg);">
							<p class="white">We employ over 15 000 people in Clicks.</p>
						</div>
					</div>
					<div class="clicks-nav light-grey-bg">
						<div class="nav-slide">
							<img src="assets/img/homepage/new_gallery/nav/2018-Gallery.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/new_gallery/nav/2018-Gallery2.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/new_gallery/nav/2018-Gallery3.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/new_gallery/nav/2018-Gallery4.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/new_gallery/nav/2018-Gallery5.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/new_gallery/nav/2018-Gallery6.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/new_gallery/nav/2018-Gallery7.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/new_gallery/nav/2018-Gallery8.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/new_gallery/nav/2018-Gallery9.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/new_gallery/nav/2018-Gallery10.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/new_gallery/nav/2018-Gallery11.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/new_gallery/nav/2018-Gallery12.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/new_gallery/nav/2018-Gallery13.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/new_gallery/nav/2018-Gallery14.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/new_gallery/nav/2018-Gallery15.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/new_gallery/nav/2018-Gallery16.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/new_gallery/nav/2018-Gallery17.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/homepage/new_gallery/nav/2018-Gallery18.jpg" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>
	</section> 

</main>

<div class="popups">
	<div class="popup video-1"></div>
	<div class="popup video-2"></div>
	<div class="popup video-3"></div>
	<div class="popup video-4"></div>
	<div class="popup video-5"></div>
	<div class="popup video-6"></div>
	<div class="popup video-7"></div>
	<div class="popup video-8"></div>
</div>

<?php include 'snippets/footer.php' ?>