<?php $title = "Clicks 2018"; ?>

<?php include 'snippets/header.php' ?>

<main>
	<div class="browser-recommend">
		<div class="window">
			<div class="popup text-center padding-15px d-flex flex-column align-items-center justify-content-center">
				<img class="margin-bottom-40px" src="assets/img/computer.png" alt="">
				<h5 class="white max-width-100">This site is best viewed on screen sizes larger than 15 inches, using the updated versions of respective browsers: <br><span class="dark-blue">Chrome, Safari, Firefox and Internet Explorer</span></h5>
				<img class="close" src="assets/img/exit.png" alt="">
			</div>
		</div>
	</div>
	
	<section class="banner-section">
		<div class="container banner-slider">
			<div class="banner banner-1 background-center">
				
			</div>
		</div>
		<div class="sky-blue-transparent-bg text-center small-content-padding">
			<h1 class="white text-uppercase margin-bottom-0">Integrated Annual Report <br><b>2018</b></h1>
		</div>
	</section>

	<section class="reports medium-content-padding">
		<div class="container">
			<div class="row d-flex">
				<div class="col-4 text-center margin-bottom-20px d-flex align-items-center justify-content-center">
					<a class="white text-uppercase dark-grey-bg d-block width-100" href="">
						Download the full <br><b><u>Integrated Annual Report</u></b> >>
					</a>
				</div>
				<div class="col-4 text-center margin-bottom-20px d-flex align-items-center justify-content-center">
					<a class="white text-uppercase dark-grey-bg d-block width-100" href="">
						Download the full <br><b><u>Annual Financial Statements</u></b> >>
					</a>
				</div>
				<div class="col-4 text-center margin-bottom-20px d-flex align-items-center justify-content-center">
					<a class="white text-uppercase dark-grey-bg d-block width-100" href="">
						Download the full <br><b><u>Five year Financial Revew</u></b> >>
					</a>
				</div>
			</div>
		</div>
	</section>

	<div class="container review small-content-padding">
		<div class="row">
			<div class="col-12 margin-bottom-20px text-center">
				<h3 class="sky-blue">Clicks Group is a retail-led healthcare group which is listed in the Food and Drug Retailers sector on the JSE.</h3>
			</div>
			<div class="col-4 d-flex margin-bottom-20px">
				<div class="dark-blue-border d-flex align-items-center justify-content-center text-center width-100">
					<p class="margin-bottom-0">Cash generated by operations exceeds <br><b class="larger sky-blue">R2 billion</b></p>
				</div>
			</div>
			<div class="col-4 d-flex margin-bottom-20px">
				<div class="dark-blue-border d-flex align-items-center justify-content-center text-center width-100">
					<p class="margin-bottom-0">Diluted HEPS up <br><b class="green larger">14.5%</b> <br>to 502 cents</p>
				</div>
			</div>
			<div class="col-4 d-flex margin-bottom-20px">
				<div class="dark-blue-border d-flex align-items-center justify-content-center text-center width-100">
					<p class="margin-bottom-0">Dividend up <br><b class="blue larger">18.4%</b> <br>to 322 cents per share</p>
				</div>
			</div>
			<div class="col-4 d-flex margin-bottom-20px">
				<div class="dark-blue-border d-flex align-items-center justify-content-center text-center width-100">
					<p class="margin-bottom-0"><b class="larger blue">R7.5 billion</b> shareholder value created</p>
				</div>
			</div>
			<div class="col-4 d-flex margin-bottom-20px">
				<div class="dark-blue-border d-flex align-items-center justify-content-center text-center width-100">
					<p class="margin-bottom-0"><b class="larger green">R518 million</b> <br>capital investment</p>
				</div>
			</div>
			<div class="col-4 d-flex margin-bottom-20px">
				<div class="dark-blue-border d-flex align-items-center justify-content-center text-center width-100">
				<p class="margin-bottom-0">Opened <b class="larger sky-blue">111</b> Clicks stores and expanded footprint to 622 stores</p>
				</div>
			</div>
			<div class="col-4 d-flex margin-bottom-20px">
				<div class="dark-blue-border d-flex align-items-center justify-content-center text-center width-100">
					<p class="margin-bottom-0"><b class="larger green">R7 million</b> active Clicks ClubCard loyalty members</p>
				</div>
			</div>
			<div class="col-4 d-flex margin-bottom-20px">
				<div class="dark-blue-border d-flex align-items-center justify-content-center text-center width-100">
					<p class="margin-bottom-0"><b class="larger blue">Level 5 BBBEE</b> <br>rating under new codes</p>
				</div>
			</div>
			<div class="col-4 d-flex margin-bottom-20px">
				<div class="dark-blue-border d-flex align-items-center justify-content-center text-center width-100">
				<p class="margin-bottom-0">First-time inclusion in <b class="larger green">FTSE4Good <br>Index</b></p>
				</div>
			</div>
		</div>
	</div>

	<div class="container">
		<div class="dash">
			<div class="green-bg circle d-flex align-items-center justify-content-center">
				<img src="assets/img/down-arrow.svg" alt="Down arrow">
			</div>
		</div>
	</div>

	<div class="container creating-value medium-content-padding">
		<div class="row">
			<div class="col-6 col-lg-5">
				<h2 class="dark-blue text-uppercase">Creating <br><span class="sky-blue">value in 2018</span></h2>
				<a href="" class="btn grey-btn">Read full report <span class="sky-blue">>></span></a>
			</div>
			<div class="col-6 col-lg-7">

			</div>
		</div>
	</div>

	
	<!-- <section class="group-profile light-blue-background section-padding">
		<div class="container">
			<div class="row">
				<div class="col-8">
					<h2 class="white text-uppercase">Group profile</h2>

					<h4 class="white">Clicks Group is a retail-led healthcare group which is listed in the Food and Drug Retailers sector on the JSE.</h4>

					<p>Founded in 1968, the group has been listed on the JSE since 1996. Following changes in South African legislation in 2003 to allow corporate pharmacy ownership, the group entered the retail pharmacy market with the opening of the first Clicks pharmacy in 2004.</p>

					<p>The group is today a leader in the healthcare market where Clicks is the country’s largest pharmacy chain with 473 in-store pharmacies and a 22.2% share of the retail pharmacy market. UPD has a 25.6% share of the private pharmaceutical wholesale market.</p>

					<a class="grey-btn text-uppercase white" href="<?php echo $baseUrl; ?>pages/group_overview/group_profile">Read full report <span class="blue">>></span></a>

					<img class="d-block float-right margin-top-60px" src="assets/img/home/group-profile.png" alt="" style="width: 460px;">
				</div>
				<div class="col-4 text-center">
					<img src="assets/img/home/segment-contribution.png" alt="" style="width: 280px;">
				</div>
			</div>
		</div>
	</section>

	<section class="videos section-padding">
		<div class="container">
			<div class="row">
				<div class="col-3 col-lg-9">
					<div class="row">
						<div class="col-12">
							<img class="margin-bottom-40px" src="assets/img/logos/main_clicks.png" alt="" style="width: 350px;">
						</div>
						<div class="col-12">
							<iframe width="560" height="315" src="https://www.youtube.com/embed/o6sMGzZuoDo?rel=0&showinfo=0" frameborder="0" allowfullscreen></iframe>
						</div>
					</div>
				</div>
				<div class="col-3 d-flex flex-column justify-content-center align-items-start">
					<h4 class="dark-blue margin-bottom-20px">"Clicks produced another strong trading performance, led by pharmacy and front shop health sales. Customers continued to respond positively to the Clicks value promotions and differentiated product ranges as the chain reported strong volume growth while gaining market share in all product categories."</h4>
					<a class="grey-btn text-uppercase white" href="<?php echo $baseUrl; ?>pages/performance/review_clicks">Read full report <span class="blue">>></span></a>
				</div>
				<div class="col-12 remove-padding">
					<div class="break">
					</div>
				</div>
				<div class="col-3 col-lg-9">
					<div class="row">
						<div class="col-12">
							<img class="margin-bottom-40px" src="assets/img/logos/upd.png" alt="" style="width: 220px;">
						</div>
						<div class="col-12">
							<iframe width="560" height="315" src="https://www.youtube.com/embed/7ASkGpa-M_4?rel=0&showinfo=0" frameborder="0" allowfullscreen></iframe>
						</div>
					</div>
				</div>
				<div class="col-3 d-flex flex-column justify-content-center align-items-start">
					<h4 class="dark-blue margin-bottom-20px">"UPD delivered double-digit sales and profit growth for the year, driven by good growth in the wholesale business. Reported turnover increased by 11.4% and UPD maintained its market-leading positions in both the pharmaceutical wholesale and bulk distribution markets."</h4>
					<a class="grey-btn text-uppercase white" href="<?php echo $baseUrl; ?>pages/performance/review_upd">Read full report <span class="blue">>></span></a>
				</div>
			</div>
		</div>
	</section>

	<section class="leadership light-blue-background section-padding">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<h2 class="white text-uppercase">Leadership</h2>
				</div>
				<div class="col-4 text-center">
					<img class="margin-bottom-40px" src="assets/img/home/chairman.png" alt="">
					<h4 class="text-uppercase white">Chairman's Report</h4>
				</div>
				<div class="col-4 text-center">
					<img class="margin-bottom-40px" src="assets/img/home/ceo.png" alt="">
					<h4 class="text-uppercase white">Chief Executive's Report</h4>
				</div>
				<div class="col-4 text-center">
					<img class="margin-bottom-40px" src="assets/img/home/cfo.png" alt="">
					<h4 class="text-uppercase white">Chief Financial Officer's Report</h4>
				</div>
			</div>
			<div class="row margin-bottom-20px">
				<div class="col-2 col-lg-4">
					<p class="dark-blue">"In a year marked by significant political instability and uncertainty, deteriorating economic conditions and consequent credit ratings downgrades, financial pressure on South&nbsp;African consumers has continued to intensify."</p>
				</div>
				<div class="col-2 col-lg-4">
					<p class="dark-blue">"Clicks delivered another strong trading performance in tough retail conditions, reporting good volume growth and increased market shares in all product categories. The brand continues to demonstrate its resilience in the current constrained spending environment, with healthcare being a necessity and beauty an affordable luxury."</p>
				</div>
				<div class="col-2 col-lg-4">
					<p class="dark-blue">"Clicks Group delivered another resilient performance in tough retail trading conditions, highlighted by robust health and beauty sales, increased margins, strong cash flows and enhanced returns to shareholders."</p>
				</div>
			</div>
			<div class="row">
				<div class="col-2 col-lg-4 text-center">
					<a class="grey-btn text-uppercase white" href="<?php echo $baseUrl; ?>pages/leadership/chairman_report">Read full report <span class="blue">>></span></a>
				</div>
				<div class="col-2 col-lg-4 text-center">
					<a class="grey-btn text-uppercase white" href="<?php echo $baseUrl; ?>pages/leadership/ceo_report">Read full report <span class="blue">>></span></a>
				</div>
				<div class="col-2 col-lg-4 text-center">
					<a class="grey-btn text-uppercase white" href="<?php echo $baseUrl; ?>pages/leadership/cfo_report">Read full report <span class="blue">>></span></a>
				</div>
			</div>
		</div>
	</section>

	<section class="overview section-padding">
		<div class="container">
			<div class="row">
				<div class="col-3 col-lg-6">
					<h2 class="blue text-uppercase">Business Overview</h2>
					<a href="<?php echo $baseUrl; ?>pages/group_overview/group_profile"><h4 class="dark-blue">Group profile <span class="blue">>></span></h4></a>
					<a href="<?php echo $baseUrl; ?>pages/group_overview/group_strategy"><h4 class="dark-blue">Group strategy <span class="blue">>></span></h4></a>
					<a href="<?php echo $baseUrl; ?>pages/group_overview/business_model"><h4 class="dark-blue">Clicks' value-creating business model <span class="blue">>></span></h4></a>
					<a href="<?php echo $baseUrl; ?>pages/group_overview/stakeholder_engagement"><h4 class="dark-blue">Stakeholder engagement <span class="blue">>></span></h4></a>
					<a href="<?php echo $baseUrl; ?>pages/group_overview/material_issues"><h4 class="dark-blue">Managing material issues <span class="blue">>></span></h4></a>
					<a href="<?php echo $baseUrl; ?>pages/group_overview/investment_case"><h4 class="dark-blue">Investment case<span class="blue">>></span></h4></a>
				</div>
				<div class="col-3 col-lg-6">
					<h2 class="blue quote"><em>"Clicks Group's strategy is to create sustainable long-term shareholder value through a retail-led health, beauty and wellness offering."</em></h2>
				</div>
			</div>
		</div>
	</section>

	<section class="governance light-blue-background section-padding">
		<div class="container">
			<div class="row">
				<div class="col-3 col-lg-6">
					<h2 class="white text-uppercase">Governance</h2>
					<a href="<?php echo $baseUrl; ?>pages/governance/bod"><h4 class="dark-blue">Board of directors</h4></a>
					<a href="<?php echo $baseUrl; ?>pages/governance/create_value_governance"><h4 class="dark-blue">Creating value through good governance</h4></a>
					<a href="<?php echo $baseUrl; ?>pages/governance/create_value_citizenship"><h4 class="dark-blue">Creating value through good citizenship</h4></a>
					<a href="<?php echo $baseUrl; ?>pages/governance/rewarding_value"><h4 class="dark-blue">Rewarding value creation</h4></a>
					<a href="<?php echo $baseUrl; ?>pages/governance/shareholder_analysis"><h4 class="dark-blue">Shareholder analysis</h4></a>
					<a href="<?php echo $baseUrl; ?>pages/governance/shareholder_diary"><h4 class="dark-blue">Shareholders' diary</h4></a>
					<a href="<?php echo $baseUrl; ?>pages/governance/corporate_info"><h4 class="dark-blue">Corporate information</h4></a>
				</div>
				<div class="col-6 d-flex align-items-center">
					<div class="row">
						<div class="col-3 col-lg-6 margin-bottom-20px d-flex justify-content-center">
							<div class="governance-blocks text-center d-flex flex-column align-items-center justify-content-center">
								<h3 class="text-uppercase white margin-bottom-20px max-width-100">Summary of the audited financial statements</h3>
								<a class="grey-btn text-uppercase white" href="assets/pdfs/Clicks_Analyst_Oct2017_screen.pdf" target="_blank">Read full report <span class="blue">>></span></a>
							</div>
						</div>
						<div class="col-3 col-lg-6 d-flex justify-content-center">
							<div class="governance-blocks text-center d-flex flex-column align-items-center justify-content-center">
								<h3 class="text-uppercase white margin-bottom-20px max-width-100">Download the full audited financial statements</h3>
								<a class="white d-flex align-items-center" href="assets/pdfs/Clicks_AFS_2017_online.pdf" target="_blank">
									<p class="float-left white text-uppercase underline remove-bottom-margin">Download</p>
									<img class="float-right" src="assets/img/icons/pdf.png" alt="" style="width: 30px;">
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="section-padding clicks-exp">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<h2 class="blue text-uppercase margin-bottom-40px">The Clicks Experience</h2>
				</div>
				<div class="col-12">
					<div class="clicks-slider">
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/home/gallery/Clicks-Experience-Gallery.jpg);">
							<p class="white">Clicks operates 622 stores in destination and convenience formats.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/home/gallery/Clicks-Experience-Gallery2.jpg);">
							<p class="white">In both formats the beauty department is the start of the customer journey through our store.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/home/gallery/Clicks-Experience-Gallery3.jpg);">
							<p class="white">We have a growing presence in the fragrance market.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/home/gallery/Clicks-Experience-Gallery4.jpg);">
							<p class="white">Sorbet is one of our exclusive brands in partnership with Sorbet salons, South Africa’s leading beauty salon brand.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/home/gallery/Clicks-Experience-Gallery5.jpg);">
							<p class="white">The Clicks Group operates the franchise for The Body Shop in southern Africa. There are 53 standalone stores and a presence in 122 Clicks stores.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/home/gallery/Clicks-Experience-Gallery6.jpg);">
							<p class="white">Clicks has over 3 000 private label products.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/home/gallery/Clicks-Experience-Gallery7.jpg);">
							<p class="white">Clicks runs more health and beauty promotions than any other retailer.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/home/gallery/Clicks-Experience-Gallery8.jpg);">
							<p class="white">Baby is a strategically important category to attract new customers.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/home/gallery/Clicks-Experience-Gallery9.jpg);">
							<p class="white">Baby is a strategically important category to attract new customers.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/home/gallery/Clicks-Experience-Gallery10.jpg);">
							<p class="white">We are the market leader in toiletries.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/home/gallery/Clicks-Experience-Gallery11.jpg);">
							<p class="white">We are the market leader in toiletries.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/home/gallery/Clicks-Experience-Gallery12.jpg);">
							<p class="white">GNC is our leading exclusive brand in supplements. </p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/home/gallery/Clicks-Experience-Gallery13.jpg);">
							<p class="white">Pharmacies are in 473 of our stores.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/home/gallery/Clicks-Experience-Gallery14.jpg);">
							<p class="white">We operate clinics in 195 of our stores.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/home/gallery/Clicks-Experience-Gallery15.jpg);">
							<p class="white">We are the market leader in small electrical appliances.</p>
						</div>
						<div class="text-center background-center gallery-img" style="background-image: url(assets/img/home/gallery/Clicks-Experience-Gallery16.jpg);">
							<p class="white">We employ over 14 000 people in Clicks.</p>
						</div>
					</div>
					<div class="clicks-nav">
						<div class="nav-slide">
							<img src="assets/img/home/gallery/nav/Clicks-Experience-Gallery.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/home/gallery/nav/Clicks-Experience-Gallery2.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/home/gallery/nav/Clicks-Experience-Gallery3.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/home/gallery/nav/Clicks-Experience-Gallery4.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/home/gallery/nav/Clicks-Experience-Gallery5.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/home/gallery/nav/Clicks-Experience-Gallery6.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/home/gallery/nav/Clicks-Experience-Gallery7.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/home/gallery/nav/Clicks-Experience-Gallery8.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/home/gallery/nav/Clicks-Experience-Gallery9.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/home/gallery/nav/Clicks-Experience-Gallery10.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/home/gallery/nav/Clicks-Experience-Gallery11.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/home/gallery/nav/Clicks-Experience-Gallery12.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/home/gallery/nav/Clicks-Experience-Gallery13.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/home/gallery/nav/Clicks-Experience-Gallery14.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/home/gallery/nav/Clicks-Experience-Gallery15.jpg" alt="">
						</div>
						<div class="nav-slide">
							<img src="assets/img/home/gallery/nav/Clicks-Experience-Gallery16.jpg" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>  -->
</main>

<?php include 'snippets/footer.php' ?>