pageinfo = [[0,0,0,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,9,0,null],
	[0,0,0,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null]];
pagedata = [ ["/","Index  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/creating-value-for-our-stakeholders/business-philosophy-and-profile","Creating value for our stakeholders &#124; Business philosophy and profile  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/creating-value-for-our-stakeholders/group-strategy","Creating value for our stakeholders &#124; Group strategy  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/creating-value-for-our-stakeholders/material-issues-risks-and-opportunities","Creating value for our stakeholders &#124; Material issues risks and opportunities  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/creating-value-for-our-stakeholders/our-business-model","Creating value for our stakeholders &#124; Our business model  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/review-and-prospects/retail-industry-and-economic-trading-environment","Review and prospects &#124; Retail industry and economic trading environment  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/review-and-prospects/chairmans-report","Review and prospects &#124; Chairmans report  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/review-and-prospects/ceos-report","Review and prospects &#124; Ceos report  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/finance-and-credit/five-year-review-of-financial-performance","Finance and credit &#124; Five year review of financial performance  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/finance-and-credit/chief-financial-officers-report","Finance and credit &#124; Chief financial officers report  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/finance-and-credit/summarised-group-annual-financial-statements","Finance and credit &#124; Summarised group annual financial statements  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/finance-and-credit/managing-the-risk-of-credit","Finance and credit &#124; Managing the risk of credit  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/finance-and-credit/ten-year-review-of-credit-performance","Finance and credit &#124; Ten year review of credit performance  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/fashion-and-brands/group-brands","Fashion and brands &#124; Group brands  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/fashion-and-brands/managing-the-risk-of-fashion","Fashion and brands &#124; Managing the risk of fashion  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/fashion-and-brands/maximising-supply-chain-efficiency","Fashion and brands &#124; Maximising supply chain efficiency  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/fashion-and-brands/managing-retail-presence","Fashion and brands &#124; Managing retail presence  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/employer-of-choice/human-capital-report","Employer of choice &#124; Human capital report  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/employer-of-choice/remuneration-committee-report","Employer of choice &#124; Remuneration committee report  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/governance/board-of-directors","Governance &#124; Board of directors  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/governance/executive-management","Governance &#124; Executive management  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/governance/corporate-governance-report","Governance &#124; Corporate governance report  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/governance/notice-to-shareholders","Governance &#124; Notice to shareholders  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/governance/shareholders-diary","Governance &#124; Shareholders diary  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/governance/administration","Governance &#124; Administration  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/independent-auditors-report","Annual financial statements &#124; Independent auditors report  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/company-statements/statements-of-financial-position","Annual financial statements &#124; Company statements &#124; Statements of financial position  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/downloads","Downloads  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/search","Search  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/creating-value-for-our-stakeholders/managing-the-risk-of-fashion","Creating value for our stakeholders &#124; Managing the risk of fashion  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/creating-value-for-our-stakeholders/managing-the-risk-of-credit","Creating value for our stakeholders &#124; Managing the risk of credit  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/creating-value-for-our-stakeholders/managing-retail-presence","Creating value for our stakeholders &#124; Managing retail presence  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/creating-value-for-our-stakeholders/adopting-leading-information-technology","Creating value for our stakeholders &#124; Adopting leading information technology  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/creating-value-for-our-stakeholders/maximising-supply-chain-efficiency","Creating value for our stakeholders &#124; Maximising supply chain efficiency  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/creating-value-for-our-stakeholders/being-the-employer-of-choice","Creating value for our stakeholders &#124; Being the employer of choice  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/creating-value-for-our-stakeholders/delivering-sustained-financial-performance","Creating value for our stakeholders &#124; Delivering sustained financial performance  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/approval-of-annual-financial-statements","Annual financial statements &#124; Approval of annual financial statements  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/certificate-by-company-secretary","Annual financial statements &#124; Certificate by company secretary  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/directors-report","Annual financial statements &#124; Directors report  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/audit-committee-report","Annual financial statements &#124; Audit committee report  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/group/statements-of-financial-position","Annual financial statements &#124; Group &#124; Statements of financial position  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/group/statements-of-comprehensive-income","Annual financial statements &#124; Group &#124; Statements of comprehensive income  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/group/statements-of-changes-in-equity","Annual financial statements &#124; Group &#124; Statements of changes in equity  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/group/statements-of-cash-flows","Annual financial statements &#124; Group &#124; Statements of cash flows  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/group/notes-to-group-annual-financial-statements-1-10","Annual financial statements &#124; Group &#124; Notes to group annual financial statements 1 10  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/group/notes-to-group-annual-financial-statements-11-20","Annual financial statements &#124; Group &#124; Notes to group annual financial statements 11 20  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/company-statements/statements-of-comprehensive-income","Annual financial statements &#124; Company statements &#124; Statements of comprehensive income  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/group/notes-to-group-annual-financial-statements-21-35","Annual financial statements &#124; Group &#124; Notes to group annual financial statements 21 35  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/company-statements/statements-of-changes-in-equity","Annual financial statements &#124; Company statements &#124; Statements of changes in equity  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/company-statements/statements-of-cash-flows","Annual financial statements &#124; Company statements &#124; Statements of cash flows  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/company-statements/notes-to-annual-financial-statements-11-14","Annual financial statements &#124; Company statements &#124; Notes to annual financial statements 11 14  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/company-statements/notes-to-annual-financial-statements-2-10","Annual financial statements &#124; Company statements &#124; Notes to annual financial statements 2 10  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/company-statements/annexure-one-details-of-subsidiary-companies","Annual financial statements &#124; Company statements &#124; Annexure one details of subsidiary companies  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/company-statements/annexure-three-details-of-participants-holdings-of-equity-based-awards","Annual financial statements &#124; Company statements &#124; Annexure three details of participants holdings of equity based awards  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/company-statements/annexure-two-details-of-subsidiary-companies","Annual financial statements &#124; Company statements &#124; Annexure two details of subsidiary companies  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""],
["/annual-financial-statements/company-statements/shareholder-information","Annual financial statements &#124; Company statements &#124; Shareholder information  &#124;  Truworths Integrated Annual Report","Creating value for our Stakeholder Business Philosophy and Profile Our Business Model Group Strategy Material Issues, Risks and Opportunities Revi...",""]];
