<?php $title = "Creating Value in 2018 - Clicks 2018"; ?>

<?php include '../../snippets/header.php' ?>

<main>
    <div class="container content-styling large-content-padding creating-value-2018">
        <div class="row">
            <?php include '../../snippets/sidebars/sidebar_about.php' ?>
            <div class="col-9 col-lg-10 side-padding">
                <h1 class="text-uppercase">Creating value in 2018</h1>
                <blockquote class="sky-blue-bg">
                    <em class="white">“Creating sustainable long-term shareholder value through a retail-led health, beauty and wellness offering.”</em>
                </blockquote>
                <h3>The Integrated Reporting Framework of the International Integrated Reporting Council (IIRC) recommends reporting to stakeholders on the six main capital resources that are applied in the creation of value. Management has chosen to adapt the IIRC capitals and apply terminology which is more commonly used in managing the business.</h3>
                <div class="scroll-horizontal">
                    <table>
                        <colgroup>
                            <col width="25%">
                            <col width="12.5%">
                            <col width="12.5%">
                            <col width="12.5%">
                            <col width="12.5%">
                            <col width="12.5%">
                            <col width="12.5%">
                        </colgroup>
                        <tr>
                            <td class="white sky-blue-bg border-bottom-thick text-center">IIRC capitals</td>
                            <td class="border-bottom-thick text-center">Financial</td>
                            <td class="border-bottom-thick text-center">Manufactured</td>
                            <td class="border-bottom-thick text-center">Intellectual</td>
                            <td class="border-bottom-thick text-center">Human</td>
                            <td class="border-bottom-thick text-center">Social and relationship</td>
                            <td class="border-bottom-thick text-center">Natural</td>
                        </tr>
                        <tr>
                            <td class="white dark-blue-bg top text-center">Clicks Group Capitals</td>
                            <td class="top text-center"><b>Financial</b></td>
                            <td class="top text-center"><b>Infrastructure</b></td>
                            <td class="top text-center"><b>Intellectual</b></td>
                            <td class="top text-center"><b>People</b></td>
                            <td class="top text-center"><b>Stakeholders</b></td>
                            <td class="top text-center"><b>Environment</b></td>
                        </tr>
                    </table>
                </div>
                <div class="line-heading">
                    <h2 class="white text-uppercase dark-blue-bg">Financial</h2>
                </div>
                <div class="row">
                    <div class="col-6 border-right-grey-dotted">
                        <h3 class="margin-bottom-20px">First-time inclusion in <br><b class="sky-blue larger">FTSE/JSE Top 40 Index</b></h3>
                        <h5>Operating profit exceeds <b class="heading-3">R2 billion</b> for the first time</h5>
                    </div>
                    <div class="col-6">
                        <h5><b class="heading-3">R2.5 billion</b> cash generated by operations</h5>
                        <h5>Diluted HEPS up <b class="heading-3">15.1%</b> to 578 cents</h5>
                        <h5>Dividend up <b class="heading-3">18%</b> to 380 cents per share</h5>
                        <h5>Return on equity of 38.2% <b class="heading-3">38.2%</b></h5>
                        <h5>Total shareholder return <b class="heading-3">32.5%</b> (10-year CAGR )</h5>
                    </div>
                </div>
                <div class="line-heading">
                    <h2 class="white text-uppercase dark-blue-bg">Infrastructure</h2>
                </div>
                <div class="row">
                    <div class="col-6 border-right-grey-dotted">
                        <h3 class="margin-bottom-20px">Opened <br><b class="green larger">41 Clicks stores</b><br>and expanded footprint to 663 stores</h3>
                        <h5><b class="heading-3">R671 million</b> capital investment in stores, supply chain and IT</h5>
                    </div>
                    <div class="col-6">
                        <div class="row">
                            <div class="col-6 d-flex align-items-center justify-content-center">
                                <img src="assets/img/clicks.png" alt="Clicks Logo" style="max-width: 170px;" class="margin-bottom-20px">
                            </div>
                            <div class="col-6 d-flex align-items-center justify-content-center">
                                <img src="assets/img/upd.png" alt="UPD Logo" style="max-width: 170px;" class="margin-bottom-20px">
                            </div>
                        </div>
                        <h5>Online store offering in-store or home delivery nationally</h5>
                        <h5><b class="heading-3">37</b> new Clicks pharmacies; total now 510</h5>
                        <h5><b class="heading-3">9</b> distribution centres across Clicks and UPD</h5>
                    </div>
                </div>
                <div class="line-heading">
                    <h2 class="white text-uppercase dark-blue-bg">Intellectual</h2>
                </div>
                <div class="row">
                    <div class="col-6 border-right-grey-dotted">
                        <img class="float-right" src="assets/img/about/p3_clubcard.png" alt="Clubcard" style="width: 120px;">
                        <h3 class="margin-bottom-20px"><b class="sky-blue larger">7.8 million</b> <br>active Clicks ClubCard loyalty members</h3>
                        <h5>Clicks increased market share in all key product categories</h5>
                        <h5>Private label and exclusive brands <b class="heading-3">22%</b> of health and beauty sales</h5>
                    </div>
                    <div class="col-6">
                        <h5><b class="heading-3">Over 700</b> new private label products launched, reflecting investment in innovation</h5>
                        <h5>Clicks remains price competitive with national retailers</h5>
                        <h5>Clicks independently rated as leading health and beauty retailer in SA</h5>
                        <h5>UPD gained share of the wholesale and distribution markets</h5>
                    </div>
                </div>
                <div class="line-heading">
                    <h2 class="white text-uppercase dark-blue-bg">People</h2>
                </div>
                <div class="row">
                    <div class="col-6 border-right-grey-dotted">
                        <h3 class="margin-bottom-20px"><b class="green larger">R1.3 billion</b> <br>paid to beneficiaries of employee share ownership programme</h3>
                    </div>
                    <div class="col-6">
                        <h5><b class="heading-3">15 067</b> permanent employees; <b class="heading-3">394</b> new jobs created</h5>
                        <h5>Recognised as Top Employer in retail sector in South Africa</h5>
                        <h5><b class="heading-3">R125 million</b> invested in employee training and development</h5>
                        <h5>Pharmacy staff turnover reduced to <b class="heading-3">15%</b></h5>
                    </div>
                </div>
                <div class="line-heading">
                    <h2 class="white text-uppercase dark-blue-bg">Stakeholders</h2>
                </div>
                <div class="row">
                    <div class="col-6 border-right-grey-dotted">
                        <h3 class="margin-bottom-20px"><b class="blue larger">R812 million</b> <br>paid to shareholders in dividends</h3>
                    </div>
                    <div class="col-6">
                        <h5>Turnover of <b class="heading-3">R29.2 billion</b> generated from customers</h5>
                        <h5><b class="heading-3">R442 million</b> cashback paid to ClubCard members</h5>
                        <h5><b class="heading-3">R3.2 billion</b> paid to employees</h5>
                        <h5><b class="heading-3">R25.2 billion</b> paid to suppliers of goods and services</h5>
                    </div>
                </div>
                <div class="line-heading">
                    <h2 class="white text-uppercase dark-blue-bg">Environment</h2>
                </div>
                <div class="row">
                    <div class="col-6 border-right-grey-dotted">
                        <h3 class="margin-bottom-20px">Included in <br><b class="green larger">FTSE4Good Index</b></h3>
                        <div class="text-center">
                            <img src="assets/img/about/p3_ftse4good_logo.png" alt="FTSE4Good Index" style="max-width: 120px;">
                        </div>
                    </div>
                    <div class="col-6">
                        <h5><b class="heading-3">64%</b> reduction in municipal water usage at head office</h5>
                        <h5><b class="heading-3">37%</b> of waste recycled</h5>
                        <h5><b class="heading-3">1 980 tons</b> of recycling in the supply chain</h5>
                        <h5>Energy and water reduction targets set to reduce carbon footprint</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<?php include '../../snippets/footer.php' ?>